// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxu5Lch8JtuJr0Ns-6V7p7YP3QbagfeSY',
    appId: '1:1007514880271:web:445bb4e87a3f233dbc167a',
    messagingSenderId: '1007514880271',
    projectId: 'dalel-a367a',
    authDomain: 'dalel-a367a.firebaseapp.com',
    storageBucket: 'dalel-a367a.firebasestorage.app',
    measurementId: 'G-1Q0XHK34BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArLpg7jORXJSvhXS-SPjfgXZcSXx_P07s',
    appId: '1:1007514880271:android:380e8e9e95c01ac2bc167a',
    messagingSenderId: '1007514880271',
    projectId: 'dalel-a367a',
    storageBucket: 'dalel-a367a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8WzqeiXVBfOZfD9Wh-7OnRhPmvrmORDY',
    appId: '1:1007514880271:ios:7e7298a3cd70794abc167a',
    messagingSenderId: '1007514880271',
    projectId: 'dalel-a367a',
    storageBucket: 'dalel-a367a.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8WzqeiXVBfOZfD9Wh-7OnRhPmvrmORDY',
    appId: '1:1007514880271:ios:7e7298a3cd70794abc167a',
    messagingSenderId: '1007514880271',
    projectId: 'dalel-a367a',
    storageBucket: 'dalel-a367a.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxu5Lch8JtuJr0Ns-6V7p7YP3QbagfeSY',
    appId: '1:1007514880271:web:e26d603a6b944eecbc167a',
    messagingSenderId: '1007514880271',
    projectId: 'dalel-a367a',
    authDomain: 'dalel-a367a.firebaseapp.com',
    storageBucket: 'dalel-a367a.firebasestorage.app',
    measurementId: 'G-GLKGLGZ0YC',
  );
}
